name: Java CD with Gradle

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 권한 부여
        run: chmod +x gradlew

      - name: 테스트 없이 빌드
        run: ./gradlew clean build -x test --stacktrace

      - name: Upload JAR file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: build/libs/ZoozooClub-0.0.1-SNAPSHOT.jar

      - name: Download JAR file artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: ./  # 다운로드할 위치
          
      - name: Jar 파일 복사중
        run: |
          scp -P ${{ secrets.WAS_SSH_PORT }} -i ${{ secrets.WAS_KEY }} \
          ./build/libs/ZoozooClub-0.0.1-SNAPSHOT.jar ${{ secrets.WAS_USERNAME }}@${{ secrets.WAS_HOST }}:/home/ubuntu/app.jar

      - name: Jar 파일 실행중
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ${{ secrets.WAS_USERNAME }}
          key: ${{ secrets.WAS_KEY }}
          port: ${{ secrets.WAS_SSH_PORT }}
          script: |
            pkill -f 'java -jar' || true
            nohup java -jar /home/ubuntu/app.jar > mylog.log 2>&1 & 
